### ISSUE TITLE
Initial Admin Password Change

### ISSUE THREAD

**Issue by kenmoini** [kenmoini/jig#2]
It'd be great if the default Admin user was made more secure forcefully...such as, detect if the Admin user is used with default credentials, if so, force Password Change.  Can be done pretty easily via route middleware I guess...

Even better, if the default Admin user is even enabled, force the creation of a new Admin user that has a real address that isn't admin@admin.com....

**Comment by kenmoini** [comment]
Honestly, this should be set in two different ways now that a container is the primary delivery vehicle.

Set a few env vars:

AUTOGEN_ADMIN: bool, default: true
ADMIN_USERNAME: string, default: "jigAdmin"
ADMIN_PASSWORD: string, default: randomly generated and set to a file/logged (like how Jenkins does it)
ADMIN_EMAIL: string, default:"admin@admin.com"

Then, upon initial login, force password change.  Do checks against the file to make sure the default isn't still set for any user.

**Comment by DustinTrap** [comment]
I love it. Implementing this means a nice layer of security by default.

**Comment by kenmoini** [comment]
Functionality introduced in ae14c6d

Delivered as PHP Artisan command `php artisan initial-setup:run` and is idempotent.  Will add a new admin user if there are no other users present in the database.  The initial-setup command will also run any migrations that need to be run.
